name: cling-environment
channels:
  - conda-forge
dependencies:
  - notebook
  - xeus-cling=0.12.1
  - openmpi
  - openmp
  - openssh
variables:
  - LIBRARY_PATH: /srv/conda/envs/notebook/lib
  - LD_LIBRARY_PATH: /srv/conda/envs/notebook/lib:$LD_LIBRARY_PATH
